# extra/generate_secrets.py
# This script is run by PlatformIO as an extra script before the build.
# It generates `src/secrets.h` from environment variables.
# Do NOT put credentials in the repository. Set these env vars locally or in CI secrets.

import os
from pathlib import Path

ssid = os.environ.get('SSID')
password = os.environ.get('PASSWORD')
use_static_ip = os.environ.get('USE_STATIC_IP', '').lower() == 'true'
static_ip = os.environ.get('STATIC_IP', '192.168.1.2')
gateway_ip = os.environ.get('GATEWAY_IP', '192.168.1.1')
subnet_mask = os.environ.get('SUBNET_MASK', '255.255.255.0')
dns1_ip = os.environ.get('DNS1_IP', '8.8.8.8')
dns2_ip = os.environ.get('DNS2_IP', '8.8.4.4')

out_path = Path('src') / 'secrets.h'

if ssid and password:
    # Build static IP configuration section
    static_ip_section = ''
    if use_static_ip:
        static_ip_section = f'''
// ========== Static IP Configuration ==========
#define USE_STATIC_IP
IPAddress staticIP({', '.join(static_ip.split('.'))});
IPAddress gateway({', '.join(gateway_ip.split('.'))});
IPAddress subnet({', '.join(subnet_mask.split('.'))});
IPAddress dns1({', '.join(dns1_ip.split('.'))});
IPAddress dns2({', '.join(dns2_ip.split('.'))});
'''

    content = f'''// Auto-generated by extra/generate_secrets.py
#ifndef SECRETS_H
#define SECRETS_H

// ========== WiFi Credentials ==========
const char* ssid     = "{ssid}";
const char* password = "{password}";{static_ip_section}
#endif // SECRETS_H
'''
    out_path.write_text(content)
    print('Generated src/secrets.h from environment variables')
else:
    # Do not overwrite if file already exists; write a placeholder only if missing
    if not out_path.exists():
        placeholder = '''// Placeholder secrets.h generated because SSID/PASSWORD env vars were not set.
#ifndef SECRETS_H
#define SECRETS_H

// ========== WiFi Credentials ==========
const char* ssid     = "YOUR_SSID";
const char* password = "YOUR_PASSWORD";

// ========== Static IP Configuration (optional) ==========
// Uncomment and adapt if needed:
// #define USE_STATIC_IP
// IPAddress staticIP(192, 168, 1, 2);
// IPAddress gateway(192, 168, 1, 1);
// IPAddress subnet(255, 255, 255, 0);
// IPAddress dns1(8, 8, 8, 8);
// IPAddress dns2(8, 8, 4, 4);

#endif // SECRETS_H
'''
        out_path.write_text(placeholder)
        print('Created placeholder src/secrets.h (no SSID/PASSWORD env vars found)')
    else:
        print('src/secrets.h already exists; leaving it unchanged')
